### ISSUE TITLE
Problem with Version 2.0.3

### ISSUE THREAD

**Issue by namorwoy** [FaserF/ha-deutschebahn#6]
### The problem

Hi
since version 2.0.1 my connection doesn't work anymore.
I get the following error when validating my Configuration.yaml:
"Invalid config for [sensor.deutschebahn]: [from] is an invalid option for [sensor.deutschebahn]. Check: sensor.deutschebahn->from. (See ?, line ?)."

My entry in Configuration.yaml is:
# Deutsche Bahn
sensor:
   - platform: deutschebahn
     from: Haslach Bad, Freiburg im Breisgau
     to: Europaplatz, Freiburg im Breisgau

template:
    -sensor:
     - name : "haslach_bad Next departure"
       state: "{{ state_attr('sensor.haslach_bad_to_europaplatz', 'next') }}"

Just updated the version to V. 2.0.3 via HACS.

### What version of Home Assistant Core has the issue?

2022.10.4

### What version of DeutscheBahn Integration has the issue?

2.0.3

### What type of installation are you running?

Home Assistant Supervised

### Example YAML snippet

```yaml
# Deutsche Bahn
sensor:
  - platform: deutschebahn
    from: Haslach Bad, Freiburg im Breisgau
    to: Europaplatz, Freiburg im Breisgau

template:
   -sensor:
    - name : "haslach_bad Next departure"
      state: "{{ state_attr('sensor.haslach_bad_to_europaplatz', 'next') }}"
```
